### ISSUE TITLE
Can I add my 100 Python Challenges Directory?

### ISSUE THREAD

**Issue by kishanrajput23** [Devs-Dungeon/Resources#1]
![image](https://user-images.githubusercontent.com/70385488/149135894-6643904a-7c58-4f8b-adfe-b066f5fe8a3c.png)

This directory contains 100 Python challenges from very basic questions to intermediate level. This will help any beginner to check their knowledge while learning python and also it contains solutions of every challenge.

Also if you approved this then let me know can I add this resource in `Resources/Programming Languages/Python/` or any other directory.

![image](https://user-images.githubusercontent.com/70385488/149135765-970da02a-e0e3-40b8-a1f6-eedb55e585bb.png)

**Comment by Neklaustares-tPtwP** [comment]
@kishanrajput23 
Sure you can add it to `Resources/Programming Languages/Python/Theory`  and there create a folder for yours to add.

Also once u add, make sure you add your name to the Contributor's list too. 
Link: https://github.com/Devs-Dungeon/Resources/blob/main/02-How%20to%20Contribute%20to%20this%20Repo/CONTRIBUTORS.md

**Comment by kishanrajput23** [comment]
Ya sure. I understood. 
Now, if you want you can close this issue.
Thanks you for response.
